version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: proespecies-user
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
  db:
    container_name: "postgresDbUser"
    image: "postgres:latest"
    ports: 
      - "5433:5432"
    volumes:
      - db_persdata:/var/lib/db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    networks:
      - default

networks:
  default:
volumes:
  db_persdata : {}