version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: eu-pescador-user
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
  db:
    container_name: "postgresDbUser"
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes:
      - db_persdata:/var/lib/db
    command: postgres -c port=5432
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default

networks:
  default:
volumes:
  db_persdata : {}